name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: try to restore cache
        uses: actions/cache@v3
        with: 
          key: cache-3287227797
          path: cacheFolder
