name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: tar version?
        run: tar --version
#         uses: mxschmitt/action-tmate@v3

      - uses: actions/cache@v3
        with:
          path: cacheFolder
          key: cache-3417611142
