name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/cache@v3
        id: cache
        with:
          path: test-cache
          key: ubuntu-latest-runner

      - if: ${{ steps.cache.outputs.cache-hit == 'true' }}
        run: echo hello
