name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:

      - name: tar version?
        run: tar --version
        shell: pwsh
#         uses: mxschmitt/action-tmate@v3
