name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - if: ${{ runner.os == 'Windows' }}
        name: Use GNU tar
        shell: cmd
        run: |
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      - name: try to restore cache
        uses: actions/cache@v3
        with: 
          key: cache-3297083611
          path: cacheFolder
