name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - uses: actions/cache@v3
        with:
          path: test-cache
          key: windows-latest-runner
