name: action test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: try to save cache
        env:
          ACTIONS_STEP_DEBUG: true
        uses: actions/cache@v3
        with: 
          key: Linux-1
