name: action test
on:
  workflow_dispatch:
env:
  ACTIONS_STEP_DEBUG: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: try to save cache
        uses: actions/cache@v3
        with: 
          key: Linux-2
          path: .
