name: apt cache
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Use Apt lists cache
        uses: actions/cache@v3
        with:
          path: /var/lib/apt/lists
          key: ${{ runner.os }}-apt-lists
      - name: Use Apt packages cache
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-packages
      - name: Install Apt dependencies
        run: |
          apt update
          apt install -y liblua5.1-dev luarocks
