name: script
on:
  workflow_dispatch:
jobs:
  some-job:
    name: Some Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
      - run: |
          python test.py
          /usr/bin/tar --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/test-repo/test-repo --files-from manifest.txt
          /usr/bin/tar --use-compress-program unzstd -tf ./cache.tzst -P
        env: 
          ACTIONS_RUNTIME_TOKEN: ${{ steps.script.outputs.TOKEN }}
