name: GH Actions Test
on:
  workflow_dispatch:
#   pull_request:
#   push:
#     branches:
#       - main
jobs:
  test:
    env:
      BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
      HEAD_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: try to restore cache from base branch
        if: github.event_name == 'pull_request'
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.BASE_SHA }}
          key: ${{ runner.os }}-${{ env.BASE_SHA }}
      - name: cache
        id: restore-cache1
        uses: actions/cache@v3
        with:
          path: ./cachepath
          key: cache-key-2
      - name: debug
        run: echo ${{ steps.restore-cache1.outputs.cache-hit }}
      - name: create file
        run: |
          mkdir cachepath
          echo "foobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobarfoobar" > ./cachepath/file
          ls -la
          ls -la cachepath
