name: Build and lint

on: [push, pull_request, workflow_dispatch]

jobs:
    build-and-lint:
        name: Build and lint
        container:
            image: node:14-alpine
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: Cache node modules
              uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: ${{ runner.os }}-yarn-
            - name: Install node modules
              run: yarn install
            - name: Lint files
              run: yarn lint
            - name: Build package
              run: yarn build
