name: test

on: [ push, workflow_dispatch ]


jobs:
  test_api:
    runs-on: ubuntu-latest 
    container:
      image: alpine
    permissions:
      contents: read
    steps:
      - name: Pull a release using REST API
        run: |
          touch text
          echo "soehting ahah" > text
      - name: Cache
        uses: actions/cache@v3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/text
          # An explicit key for restoring and saving the cache
          key: vcpkg-${RUNNER_OS}-${GITHUB_BASE_REF}-kfjwdslkjfljhj
#       - name: Delete
#         run: |
#           rm -f text
#       - name: retreive
#         uses: actions/cache@v3
#         with:
#           # A list of files, directories, and wildcard patterns to cache and restore
#           path: text
#           key: vcpkg-${RUNNER_OS}-${GITHUB_BASE_REF}-kfjwdslkjfljhj
      - name: test response
        run: |
          cat text
