name: Version of OS
on: 
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: env
        run: env
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: env
  Windows:
    runs-on: windows-latest
    steps:
      - name: env
        run: env
