name: python conda
on: workflow_dispatch

defaults:
  run:
    shell: bash -l {0}

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: MY_ENV
          auto-activate-base: false

      - name: Establish Conda environment directory
        id: conda_env
        run: |
          conda info --json | jq -r '"::set-output name=dir::\(.envs_dirs[0])"'

      - name: Setup Conda environment caching
        id: cache
        uses: actions/cache@v3
        env:
          # Increase this to manually invalidate the cache
          CACHE_NUMBER: 0
        with:
          path: ${{ steps.conda_env.outputs.dir }}
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml', 'requirements.txt') }}-${{ env.CACHE_NUMBER }}

      - name: Update Conda environment
        run: conda env update -n MY_ENV -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
