name: test

on: [ push, workflow_dispatch ]


jobs:
  e2e-job:
    runs-on: ubuntu-latest
#     container: python:3.9
    services:
      elasticsearch:
        image: elasticsearch:7.14.1
        env:
          'discovery.type': single-node
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache pip dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-pip-dependencies-5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
#       - name: Run tests
#         env:
#           ELASTICSEARCH_HOST: elasticsearch
#         run: make dev-test
