name: GH Actions Test
on:
  workflow_dispatch:
#   pull_request:
#   push:
#     branches:
#       - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: try to restore cache from base branch
        id: restore-cache
        uses: actions/cache@v3
        with:
          path: cacheFolder
          key: 1234567890123456789012345678901234567999999
      - name: debug
        run: |
            echo ${{ steps.restore-cache.outputs.cache-hit }}
            echo ${{ github.ref }}
      - name: create file
        run: |
          mkdir -p cacheFolder 2>/dev/null && echo 'foo' > "cacheFolder/foo.txt"
