name: Testing actions cache
on: 
  release:
    types: [created]
jobs:
  CreateV3:
    runs-on: ubuntu-latest
    steps:
    - name: Cache URL
      uses: actions/github-script@v5
      with:
        script: |
          const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
          console.log("ACTIONS_CACHE_URL_VAL="+process.env['ACTIONS_CACHE_URL']);
 
    - name: Create Cache Folder
      run: |
        rm -rf cache-folder
        mkdir cache-folder
        
    - uses: actions/cache@v3
      id: cache
      with:
        path: cache-folder
        key: ${{ runner.os }}-${{ github.sha }}-key-1

    - name: Creating Content
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd cache-folder
        dd if=/dev/urandom of=file.txt count=100 bs=1048576
        cat file.txt | openssl dgst -sha256 > sha256.txt
