name: Example
on:
  workflow_dispatch:
jobs:
  some-job:
    name: Some Job
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir this that
          cd this
          dd if=/dev/urandom of=file.txt count=100 bs=1048576
          cat file.txt | openssl dgst -sha256 > sha256.txt
          
        
      - name: Setup some cache
        id: some-cache
        uses: actions/cache@v3
        with:
          key: ${{ echo $ImageOS }}-some-key
          path: | 
            this
