name: node packages
on: workflow_dispatch

jobs:
  foo:
    runs-on: windows-latest
    steps:
      - run: pwd
      - run: |
          echo ${{ github.workspace }}
          env
          pwd
        working-directory: /c/Users/runneradmin
