name: node packages
on: workflow_dispatch

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          #git clone https://github.com/telescopejs/telescope.git
          git clone https://github.com/atom/atom.git
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          cd atom
          npm install
          du -sh node_modules
