name: node packages
on: workflow_dispatch

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.workspace }}
        run: echo hello
      - name: ${{ env.HOME }}
        run: echo hello
