name: node packages
on: workflow_dispatch

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: git clone https://github.com/telescopejs/telescope.git
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - run: |
          cd telescope
          npm install
          ls
          du node_modules
